# Generated by Django 4.2.4 on 2023-08-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_blog_body_alter_blog_author_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(default=None, upload_to='uploads/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
